old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        send_message:
            connection:       default
            exchange_options: {name: 'send_message', type: direct}
            service_alias:    my_app_service # no alias by default
            queue_options:   {name: 'send_message'}
    consumers:
        send_message:
            connection:       default
            exchange_options: {name: 'send_message', type: direct}
            queue_options:    {name: 'send_message'}
            callback:         App\Service\SendMessageProcess
            enable_logger:    true
