security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: text
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost:      12
