security:
    providers:
        in_memory: { memory: ~ }

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

    access_control:
        - { path: ^/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
