language: php

dist: trusty
sudo: false

git:
    depth: 1

addons:
    apt_packages:
        - parallel
        - language-pack-fr-base
        - ldap-utils
        - slapd

env:
    global:
        - MIN_PHP=7.1.3
        - SYMFONY_PROCESS_PHP_TEST_BINARY=~/.phpenv/shims/php

matrix:
    include:
        - php: 7.1.3
        - php: 7.1
          env: deps=high
        - php: 7.2
          env: deps=low

    fast_finish: true

cache:
    directories:
        - .phpunit
        - php-$MIN_PHP
        - php-ext

services:
    - redis-server
