login:
   path:       /login
   controller: App\Controller\User\SecurityController::login
   methods:    [GET, POST]

register:
   path: /register
   controller: App\Controller\User\RegistrationController::registerAction

message:
   path: /message
   controller: App\Controller\Message\MessageController::message

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /message
        permanent: true

logout:
    path: /logout
