login:
   path: /login
   controller: App\Controller\LoginController::login

register:
   path: /register
   controller: App\Controller\RegistrationController::register

text:
   path: /text
   controller: App\Controller\TextController::text