login:
   path:       /login
   controller: App\Controller\User\SecurityController::login
   methods:    [GET, POST]

register:
   path: /register
   controller: App\Controller\User\RegistrationController::registerAction

text:
   path: /text
   controller: App\Controller\Text\TextController::text

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /text
        permanent: true

logout:
    path: /logout
