login:
   path:       /login
   controller: App\Controller\LoginController::login
   methods:    [GET, POST]

register:
   path: /register
   controller: App\Controller\RegistrationController::register

text:
   path: /text
   controller: App\Controller\TextController::text

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /text
        permanent: true
