login:
    path:       /login
    controller: App\Controller\User\SecurityController::login
    methods:    [GET, POST]

register:
    path: /register
    controller: App\Controller\User\RegistrationController::registerAction

message:
    path: /message
    controller: App\Controller\Message\MessageController::message

messages:
    path: /messages/{page}
    controller: App\Controller\Message\MessagesController::viewAll
    defaults:
        page: 1
    requirements:
        page: '\d+'

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /message
        permanent: true

logout:
    path: /logout
